### ISSUE TITLE
json instead of markdown?

### ISSUE THREAD

**Issue by justfunk** [yeojz/metalsmith-react-templates#42]
Hi. Thanks a lot for this nice plugin!
Is it possible to store my data into json files instead of markdown files in the /src/ directory?

**Comment by yeojz** [comment]
@justfunk should not be a problem.

Metalsmith reads all files in the directory.
As for this plugin, you can set the pattern to only read from json
`pattern: **/*.json`

Contents of the file will still be in the content prop.

**Comment by yeojz** [comment]
@justfunk 
Closing this. Please reopen if needed.
Thanks!

**Comment by ablackledge** [comment]
Hi @yeojz , I'm also want to use json instead of markdown for the data I'll pass into the React template, when I've added a json file although it is being read and used it's just interpreted as one big string. Is there something I need to do so that it's being treated as a proper json object?

Thanks

**Comment by yeojz** [comment]
@ablackledge you'll probably need to use `JSON.parse()` on the value.

**Comment by ablackledge** [comment]
Oh damn sorry, so simple should have come to that conclusion myself! 😳
Thanks for the quick reply
